version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-latest"

python:
  install:
    - method: pip
      path: .

conda:
  environment: environment.doc.yml
  
sphinx:
  builder: html
  configuration: doc/conf.py
  fail_on_warning: false
