version: 2

python:
  version: 3.8
  install: 
    - method: pip
      path: .

sphinx:
  builder: html
  configuration: doc/conf.py
  fail_on_warning: false

build:
  image: latest

conda:
  environment: environment_dev.yml