os: linux
dist: trusty
language: python

install:
  - deactivate
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH=$HOME/miniconda/bin:$PATH
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - conda update --yes conda
  - conda create -n test-env --yes python=$TRAVIS_PYTHON_VERSION flake8 mypy scikit-learn pytest
  - conda activate test-env

script:
  - flake8 . --exclude doc,setup.py --max-line-length=120
  # - mypy . --strict --config-file mypy.ini
  - pytest -s mapie/tests
