build: false

environment:
  matrix:    
    - PYTHON: "C:\\Miniconda3-x64"
      PYTHON_VERSION: "3.7.x"
    
    - PYTHON: "C:\\Miniconda3-x64"
      PYTHON_VERSION: "3.8.x"
    
    - PYTHON: "C:\\Miniconda3-x64"
      PYTHON_VERSION: "3.9.x"

matrix:
  fast_finish: true

install:
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PYTHON%\\Library\\bin;%PATH%
  - python --version
  - conda update --yes conda
  - conda install --yes -c conda-forge codecov flake8 mypy numpy>=1.20 scikit-learn pytest-cov

test_script:
  - flake8 . --exclude doc --max-line-length=120
  # - mypy mapie examples --strict --config-file mypy.ini
  - pytest --cov-branch --cov=mapie --pyargs mapie

after_test:
  - codecov
