name: mapie
channels:
    - defaults
    - conda-forge
dependencies:
    - numpy=1.20.2
    - numpydoc=1.1.0
    - python=3.9.2
    - scikit-learn=0.24.1
    - sphinx=3.5.3
    - sphinx-gallery=0.8.2
    - sphinx_rtd_theme=0.5.2