name: mapie_notebooks
channels:
    - defaults
    - conda-forge
dependencies:
    - ipykernel=6.4.1
    - jupyter=1.0.0
    - jupyterlab=3.0.16
    - jupytext=1.11.2
    - nbconvert=6.4.0
    - pandas=1.2.4
    - pip=21.0.1
    - pip:
        - scikeras==0.3.3
        - tensorflow==2.7.0
    - python=3.9.2
    - scikit-learn=1.0.0
    - xgboost=1.3.0
