name: mapie-doc
channels:
    - defaults
    - conda-forge
dependencies:
    - lightgbm=3.2.1
    - numpydoc=1.1.0
    - pandas=1.3.5
    - python=3.10
    - scikit-learn=1.5.0
    - sphinx=5.3.0
    - sphinx-gallery=0.16.0
    - sphinx_rtd_theme=2.0.0
    - typing_extensions=4.0.1
