version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9.4
    steps:
      - checkout
      - run: 
          name: install dependencies
          command: |
              wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
              chmod +x miniconda.sh 
              bash miniconda.sh -b -p $HOME/miniconda
              export PATH=$HOME/miniconda/bin:$PATH
              source $HOME/miniconda/etc/profile.d/conda.sh
              conda update --yes conda
              conda create -n test-env --yes -c conda-forge python=3.9 numpy>=1.20 numpydoc scikit-learn matplotlib sphinx sphinx-gallery sphinx_rtd_theme
              conda activate test-env
              conda env export
              pip install .
      - run: 
          name: build documentation
          command: |
              cd doc
              make html
      - store_artifacts:
          path: doc/_build/html/
          destination: doc
      - store_artifacts:
          path: ~/log.txt
      - run: ls -ltrh doc/_build/html

workflows:
  version: 2
  workflow:
    jobs:
      - build
