name: Unit tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: 3.7
            numpy-version: 1.18.5
          - os: ubuntu-latest
            python-version: 3.8
            numpy-version: 1.19.5
          - os: ubuntu-latest
            python-version: 3.9
            numpy-version: 1.20.3
          - os: windows-latest
            python-version: 3.7
            numpy-version: 1.18.5
          - os: windows-latest
            python-version: 3.8
            numpy-version: 1.19.5
          - os: windows-latest
            python-version: 3.9
            numpy-version: 1.20.3
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - name: Git clone
      uses: actions/checkout@v2
    - name: Set up virtual environment
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        channels: defaults, conda-forge
    - name: Install dependencies
      run: conda install codecov flake8 mypy numpy=${{ matrix.numpy-version }} scikit-learn pandas pytest-cov typed-ast
    - name: Check linting
      run: flake8 . --exclude=doc
    - name: Check static typing
      run: mypy mapie examples --strict
    - name: Test with pytest
      run: pytest -vs --doctest-modules --cov-branch --cov=mapie --pyargs mapie
    - name: Code coverage
      run: codecov
